"""empty message

Revision ID: 31252b506609
Revises: a3dfc4a4bded
Create Date: 2023-02-03 10:12:57.172449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31252b506609'
down_revision = 'a3dfc4a4bded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
